<?php

    /*!
     * https://raccoonsquare.com
     * raccoonsquare@gmail.com
     *
     * Copyright 2012-2021 Demyanchuk Dmitry (raccoonsquare@gmail.com)
     */

$C['VIDEO_FILE_MAX_SIZE'] = 10485760; //Max size for video file in bytes | For example 10mb = 10*1024*1024
$C['IMAGE_FILE_MAX_SIZE'] = 5242880;  //Max size for image file in bytes | For example 5mb = 5*1024*1024

$C['UPGRADES_GHOST_MODE_COST'] = 150;
$C['UPGRADES_VERIFIED_BADGE_COST'] = 100;
$C['UPGRADES_DISABLE_ADS_COST'] = 200;

$C['ADMIN_ACCESS_LEVEL_ALL_RIGHTS'] = 0;
$C['ADMIN_ACCESS_LEVEL_READ_WRITE_RIGHTS'] = 1;
$C['ADMIN_ACCESS_LEVEL_MODERATOR_RIGHTS'] = 2;
$C['ADMIN_ACCESS_LEVEL_READ_ONLY_RIGHTS'] = 3;

$C['API_VERSION'] = "v2";

$C['APP_TYPE_ALL'] = -1;
$C['APP_TYPE_MANAGER'] = 0;
$C['APP_TYPE_WEB'] = 1;
$C['APP_TYPE_ANDROID'] = 2;
$C['APP_TYPE_IOS'] = 3;

$C['GCM_NOTIFY_VIDEO_COMMENT_REPLY'] = 21;
$C['GCM_NOTIFY_VIDEO_COMMENT'] = 22;
$C['GCM_NOTIFY_VIDEO_LIKE'] = 23;

$C['GCM_NOTIFY_REFERRAL'] = 24;

$C['GCM_NOTIFY_MATCH'] = 25;

$C['GCM_NOTIFY_TYPING_START'] = 27;
$C['GCM_NOTIFY_TYPING_END'] = 28;

$C['GCM_NOTIFY_MEDIA_APPROVE'] = 1001;
$C['GCM_NOTIFY_MEDIA_REJECT'] = 1002;
$C['GCM_NOTIFY_PROFILE_PHOTO_APPROVE'] = 1003;
$C['GCM_NOTIFY_PROFILE_PHOTO_REJECT'] = 1004;
$C['GCM_NOTIFY_ACCOUNT_APPROVE'] = 1005;
$C['GCM_NOTIFY_ACCOUNT_REJECT'] = 1006;
$C['GCM_NOTIFY_PROFILE_COVER_APPROVE'] = 1007;
$C['GCM_NOTIFY_PROFILE_COVER_REJECT'] = 1008;

$C['GCM_NOTIFY_CHANGE_ACCOUNT_SETTINGS'] = 30;

$C['GCM_NOTIFY_PROFILE_NEW_PROFILE_PHOTO_UPLOADED'] = 2001;
$C['GCM_NOTIFY_PROFILE_NEW_PROFILE_COVER_UPLOADED'] = 2002;
$C['GCM_NOTIFY_PROFILE_NEW_MEDIA_ITEM_UPLOADED'] = 2003;

$C['NOTIFY_TYPE_MEDIA_APPROVE'] = 10;
$C['NOTIFY_TYPE_MEDIA_REJECT'] = 11;
$C['NOTIFY_TYPE_PROFILE_PHOTO_APPROVE'] = 12;
$C['NOTIFY_TYPE_PROFILE_PHOTO_REJECT'] = 13;
$C['NOTIFY_TYPE_ACCOUNT_APPROVE'] = 14;
$C['NOTIFY_TYPE_ACCOUNT_REJECT'] = 15;
$C['NOTIFY_TYPE_PROFILE_COVER_APPROVE'] = 16;
$C['NOTIFY_TYPE_PROFILE_COVER_REJECT'] = 17;

$C['IMAGE_TYPE_PROFILE_PHOTO'] = 0;
$C['IMAGE_TYPE_PROFILE_COVER'] = 1;

$C['REPORT_TYPE_ITEM'] = 0;
$C['REPORT_TYPE_PROFILE'] = 1;
$C['REPORT_TYPE_MESSAGE'] = 2;
$C['REPORT_TYPE_COMMENT'] = 3;
$C['REPORT_TYPE_GALLERY_ITEM'] = 4;
$C['REPORT_TYPE_MARKET_ITEM'] = 5;
$C['REPORT_TYPE_COMMUNITY'] = 6;

$C['ITEM_TYPE_IMAGE'] = 0;
$C['ITEM_TYPE_VIDEO'] = 1;
$C['ITEM_TYPE_POST'] = 2;
$C['ITEM_TYPE_COMMENT'] = 3;
$C['ITEM_TYPE_GALLERY'] = 4;

// Payments

// PA - PAYMENT ACTION
$C['PA_BUY_CREDITS'] = 0;
$C['PA_BUY_GIFT'] = 1;
$C['PA_BUY_VERIFIED_BADGE'] = 2;
$C['PA_BUY_GHOST_MODE'] = 3;
$C['PA_BUY_DISABLE_ADS'] = 4;
$C['PA_BUY_REGISTRATION_BONUS'] = 5;
$C['PA_BUY_REFERRAL_BONUS'] = 6;
$C['PA_BUY_MANUAL_BONUS'] = 7;
$C['PA_BUY_PRO_MODE'] = 8;
$C['PA_BUY_SPOTLIGHT'] = 9;
$C['PA_BUY_MESSAGE_PACKAGE'] = 10;
$C['PA_SEND_TRANSFER'] = 11;
$C['PA_RECEIVE_TRANSFER'] = 12;

// PT - PAYMENT TYPE
$C['PT_UNKNOWN'] = 0;
$C['PT_CREDITS'] = 1;
$C['PT_CARD'] = 2;
$C['PT_GOOGLE_PURCHASE'] = 3;
$C['PT_APPLE_PURCHASE'] = 4;
$C['PT_ADMOB_REWARDED_ADS'] = 5;
$C['PT_BONUS'] = 6;

$C['CURRENCY_USD'] = 0;
$C['CURRENCY_EUR'] = 1;

// Errors

$C['ERROR_CLIENT_ID'] = 19100;
$C['ERROR_CLIENT_SECRET'] = 19101;

$C['ERROR_FILE_SIZE_BIG'] = 501;
$C['ERROR_FILE_SIZE_SMALL'] = 502;

$C['ERROR_IMAGE_FILE_FORMAT'] = 503;
$C['ERROR_IMAGE_FILE_WIDTH_HEIGHT'] = 504;

$C['ERROR_VIDEO_FILE_FORMAT'] = 505;

$C['ERROR_OTP_VERIFICATION'] = 506;
$C['ERROR_OTP_PHONE_NUMBER_TAKEN'] = 507;

// Verification

$C['ENVATO_ITEM_ID'] = 14781822; // Dating App Item Id

$C['ENVATO_ERROR_PCODE_UNKNOWN'] = 90000;
$C['ENVATO_ERROR_PCODE_INVALID'] = 90001;
$C['ENVATO_ERROR_PCODE_VERIFIED'] = 90002;
$C['ENVATO_ERROR_PCODE_REGISTERED'] = 90003;
$C['ENVATO_ERROR_PCODE_ILLEGAL'] = 90004;